package com.rosf73.garcani.localdata

object Tarot {

    // card-name to image-link
    val data = mapOf(
        "The Fool" to "https://upload.wikimedia.org/wikipedia/commons/9/90/RWS_Tarot_00_Fool.jpg",
        "The Magician" to "https://upload.wikimedia.org/wikipedia/commons/d/de/RWS_Tarot_01_Magician.jpg",
        "The High Priestess" to "https://upload.wikimedia.org/wikipedia/commons/8/88/RWS_Tarot_02_High_Priestess.jpg",
        "The Empress" to "https://upload.wikimedia.org/wikipedia/commons/d/d2/RWS_Tarot_03_Empress.jpg",
        "The Emperor" to "https://upload.wikimedia.org/wikipedia/commons/c/c3/RWS_Tarot_04_Emperor.jpg",
        "The Hierophant" to "https://upload.wikimedia.org/wikipedia/commons/8/8d/RWS_Tarot_05_Hierophant.jpg",
        "The Lovers" to "https://upload.wikimedia.org/wikipedia/commons/3/3a/TheLovers.jpg",
        "The Chariot" to "https://upload.wikimedia.org/wikipedia/commons/9/9b/RWS_Tarot_07_Chariot.jpg",
        "Strength" to "https://upload.wikimedia.org/wikipedia/commons/f/f5/RWS_Tarot_08_Strength.jpg",
        "The Hermit" to "https://upload.wikimedia.org/wikipedia/commons/4/4d/RWS_Tarot_09_Hermit.jpg",
        "Wheel of Fortune" to "https://upload.wikimedia.org/wikipedia/commons/3/3c/RWS_Tarot_10_Wheel_of_Fortune.jpg",
        "Justice" to "https://upload.wikimedia.org/wikipedia/commons/e/e0/RWS_Tarot_11_Justice.jpg",
        "The Hanged Man" to "https://upload.wikimedia.org/wikipedia/commons/2/2b/RWS_Tarot_12_Hanged_Man.jpg",
        "Death" to "https://upload.wikimedia.org/wikipedia/commons/d/d7/RWS_Tarot_13_Death.jpg",
        "Temperance" to "https://upload.wikimedia.org/wikipedia/commons/f/f8/RWS_Tarot_14_Temperance.jpg",
        "The Devil" to "https://upload.wikimedia.org/wikipedia/commons/5/55/RWS_Tarot_15_Devil.jpg",
        "The Tower" to "https://upload.wikimedia.org/wikipedia/commons/5/53/RWS_Tarot_16_Tower.jpg",
        "The Star" to "https://upload.wikimedia.org/wikipedia/commons/d/db/RWS_Tarot_17_Star.jpg",
        "The Moon" to "https://upload.wikimedia.org/wikipedia/commons/7/7f/RWS_Tarot_18_Moon.jpg",
        "The Sun" to "https://upload.wikimedia.org/wikipedia/commons/1/17/RWS_Tarot_19_Sun.jpg",
        "Judgment" to "https://upload.wikimedia.org/wikipedia/commons/d/dd/RWS_Tarot_20_Judgement.jpg",
        "The World" to "https://upload.wikimedia.org/wikipedia/commons/f/ff/RWS_Tarot_21_World.jpg",
        "Ace of Wands" to "https://upload.wikimedia.org/wikipedia/commons/1/11/Wands01.jpg",
        "Two of Wands" to "https://upload.wikimedia.org/wikipedia/commons/0/0f/Wands02.jpg",
        "Three of Wands" to "https://upload.wikimedia.org/wikipedia/commons/f/ff/Wands03.jpg",
        "Four of Wands" to "https://upload.wikimedia.org/wikipedia/commons/a/a4/Wands04.jpg",
        "Five of Wands" to "https://upload.wikimedia.org/wikipedia/commons/9/9d/Wands05.jpg",
        "Six of Wands" to "https://upload.wikimedia.org/wikipedia/commons/3/3b/Wands06.jpg",
        "Seven of Wands" to "https://upload.wikimedia.org/wikipedia/commons/e/e4/Wands07.jpg",
        "Eight of Wands" to "https://upload.wikimedia.org/wikipedia/commons/6/6b/Wands08.jpg",
        "Nine of Wands" to "https://upload.wikimedia.org/wikipedia/commons/4/4d/Tarot_Nine_of_Wands.jpg",
        "Ten of Wands" to "https://upload.wikimedia.org/wikipedia/commons/0/0b/Wands10.jpg",
        "Page of Wands" to "https://upload.wikimedia.org/wikipedia/commons/6/6a/Wands11.jpg",
        "Knight of Wands" to "https://upload.wikimedia.org/wikipedia/commons/1/16/Wands12.jpg",
        "Queen of Wands" to "https://upload.wikimedia.org/wikipedia/commons/0/0d/Wands13.jpg",
        "King of Wands" to "https://upload.wikimedia.org/wikipedia/commons/c/ce/Wands14.jpg",
        "Ace of Cups" to "https://upload.wikimedia.org/wikipedia/commons/3/36/Cups01.jpg",
        "Two of Cups" to "https://upload.wikimedia.org/wikipedia/commons/f/f8/Cups02.jpg",
        "Three of Cups" to "https://upload.wikimedia.org/wikipedia/commons/7/7a/Cups03.jpg",
        "Four of Cups" to "https://upload.wikimedia.org/wikipedia/commons/3/35/Cups04.jpg",
        "Five of Cups" to "https://upload.wikimedia.org/wikipedia/commons/d/d7/Cups05.jpg",
        "Six of Cups" to "https://upload.wikimedia.org/wikipedia/commons/1/17/Cups06.jpg",
        "Seven of Cups" to "https://upload.wikimedia.org/wikipedia/commons/a/ae/Cups07.jpg",
        "Eight of Cups" to "https://upload.wikimedia.org/wikipedia/commons/6/60/Cups08.jpg",
        "Nine of Cups" to "https://upload.wikimedia.org/wikipedia/commons/2/24/Cups09.jpg",
        "Ten of Cups" to "https://upload.wikimedia.org/wikipedia/commons/8/84/Cups10.jpg",
        "Page of Cups" to "https://upload.wikimedia.org/wikipedia/commons/a/ad/Cups11.jpg",
        "Knight of Cups" to "https://upload.wikimedia.org/wikipedia/commons/f/fa/Cups12.jpg",
        "Queen of Cups" to "https://upload.wikimedia.org/wikipedia/commons/6/62/Cups13.jpg",
        "King of Cups" to "https://upload.wikimedia.org/wikipedia/commons/0/04/Cups14.jpg",
        "Ace of Swords" to "https://upload.wikimedia.org/wikipedia/commons/1/1a/Swords01.jpg",
        "Two of Swords" to "https://upload.wikimedia.org/wikipedia/commons/9/9e/Swords02.jpg",
        "Three of Swords" to "https://upload.wikimedia.org/wikipedia/commons/0/02/Swords03.jpg",
        "Four of Swords" to "https://upload.wikimedia.org/wikipedia/commons/b/bf/Swords04.jpg",
        "Five of Swords" to "https://upload.wikimedia.org/wikipedia/commons/2/23/Swords05.jpg",
        "Six of Swords" to "https://upload.wikimedia.org/wikipedia/commons/2/29/Swords06.jpg",
        "Seven of Swords" to "https://upload.wikimedia.org/wikipedia/commons/3/34/Swords07.jpg",
        "Eight of Swords" to "https://upload.wikimedia.org/wikipedia/commons/a/a7/Swords08.jpg",
        "Nine of Swords" to "https://upload.wikimedia.org/wikipedia/commons/2/2f/Swords09.jpg",
        "Ten of Swords" to "https://upload.wikimedia.org/wikipedia/commons/d/d4/Swords10.jpg",
        "Page of Swords" to "https://upload.wikimedia.org/wikipedia/commons/4/4c/Swords11.jpg",
        "Knight of Swords" to "https://upload.wikimedia.org/wikipedia/commons/b/b0/Swords12.jpg",
        "Queen of Swords" to "https://upload.wikimedia.org/wikipedia/commons/d/d4/Swords13.jpg",
        "King of Swords" to "https://upload.wikimedia.org/wikipedia/commons/3/33/Swords14.jpg",
        "Ace of Pentacles" to "https://upload.wikimedia.org/wikipedia/commons/f/fd/Pents01.jpg",
        "Two of Pentacles" to "https://upload.wikimedia.org/wikipedia/commons/9/9f/Pents02.jpg",
        "Three of Pentacles" to "https://upload.wikimedia.org/wikipedia/commons/4/42/Pents03.jpg",
        "Four of Pentacles" to "https://upload.wikimedia.org/wikipedia/commons/3/35/Pents04.jpg",
        "Five of Pentacles" to "https://upload.wikimedia.org/wikipedia/commons/9/96/Pents05.jpg",
        "Six of Pentacles" to "https://upload.wikimedia.org/wikipedia/commons/a/a6/Pents06.jpg",
        "Seven of Pentacles" to "https://upload.wikimedia.org/wikipedia/commons/6/6a/Pents07.jpg",
        "Eight of Pentacles" to "https://upload.wikimedia.org/wikipedia/commons/4/49/Pents08.jpg",
        "Nine of Pentacles" to "https://upload.wikimedia.org/wikipedia/commons/f/f0/Pents09.jpg",
        "Ten of Pentacles" to "https://upload.wikimedia.org/wikipedia/commons/4/42/Pents10.jpg",
        "Page of Pentacles" to "https://upload.wikimedia.org/wikipedia/commons/e/ec/Pents11.jpg",
        "Knight of Pentacles" to "https://upload.wikimedia.org/wikipedia/commons/d/d5/Pents12.jpg",
        "Queen of Pentacles" to "https://upload.wikimedia.org/wikipedia/commons/8/88/Pents13.jpg",
        "King of Pentacles" to "https://upload.wikimedia.org/wikipedia/commons/1/1c/Pents14.jpg",
    )

    val cards get() = data.keys
}
